import React, { useState } from "react";
import "./About.css";

const About = () => {
  const [activeIndex, setActiveIndex] = useState(null);

  const toggleAccordion = (index) => {
    setActiveIndex(index === activeIndex ? null : index);
  };

  return (
    <>
      <section className="about-page">
        <div className="about-header">
          <h1 className="about-title">
            About <span className="highlight">Us</span>
          </h1>
          <p className="about-desc">
            At BlitzURL, we believe in the power of simplicity. In a digital
            landscape inundated with lengthy URLs, we strive to provide a
            solution that streamlines the sharing process. Our platform empowers
            users to transform cumbersome web addresses into concise, memorable
            links with just a click. Whether you're sharing content on social
            media, sending emails, or presenting information, our tool ensures
            that your message remains clear and easily accessible. With a
            commitment to user-friendly design and reliable functionality, we're
            dedicated to making the process of shortening URLs effortless and
            efficient. Join us on our mission to simplify the web, one link at a
            time.
          </p>
        </div>

        <div className="container">
          <h2>Frequently <span className="highlight">Asked</span> Questions</h2>
          <div className="accordion">
            {faqData.map((item, index) => (
              <div className="accordion-item" key={index}>
                <a
                  className={index === activeIndex ? "active" : ""}
                  onClick={() => toggleAccordion(index)}
                >
                  {item.question}
                </a>
                <div
                  className={`content ${index === activeIndex ? "active" : ""}`}
                >
                  <p>{item.answer}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>
    </>
  );
};

// Dummy data for FAQ items
const faqData = [
  {
    question: "What is a short URL?",
    answer:
      "A short URL is a condensed version of a long URL, making it easier to share and remember. It typically redirects to the original, longer URL.",
  },
  {
    question: "How does a short URL service work?",
    answer:
      "A short URL service takes a long URL inputted by the user and generates a shorter, unique URL. When someone clicks on the short URL, they are redirected to the original, longer URL.",
  },
  {
    question: "Why would I use a short URL?",
    answer:
      "Short URLs are useful for sharing links on platforms with character limits, such as Twitter, or when you want to make a URL more manageable and visually appealing.",
  },
  {
    question: "Are short URLs safe?",
    answer:
      "Short URLs generated by reputable services are generally safe to use. However, it's essential to be cautious of short URLs from unknown sources, as they could potentially lead to malicious websites.",
  },
  {
    question: "Do short URLs expire?",
    answer:
      "It depends on the short URL service. Some short URL services offer permanent links, while others may expire after a certain period of inactivity.",
  },
  {
    question: "Can I customize short URLs?",
    answer:
      "Some short URL services offer customization options, allowing users to choose a specific alias for their short URL. This can make the link more personalized and branded.",
  },
  {
    question: "Is there a limit to how many URLs I can shorten?",
    answer:
      "Short URL services typically have limits on the number of URLs users can shorten, especially for free accounts. Paid plans often offer higher limits or unlimited URL shortening.",
  },
  {
    question: "Do short URLs affect SEO?",
    answer:
      "Short URLs themselves do not directly impact SEO. However, using short URLs can make it easier for users to share and access your content, potentially increasing traffic to your website, which can indirectly benefit your SEO efforts.",
  },
  {
    question: "Can I track the performance of my short URLs?",
    answer:
      "Many short URL services offer analytics features that allow users to track the number of clicks, geographic location of visitors, and other metrics for their short URLs.",
  },
];
export default About;
